CREATE VIEW V_RESERVAS
AS
SELECT DIA,MES,HORA,CODAULA,CODGRUPO,APELLIDOS,NOMBRE FROM RESERVAS,PROFES
WHERE DNI = DNIPROF;

CREATE OR REPLACE TRIGGER ALTA_RESERVA
INSTEAD OF 
INSERT ON V_RESERVAS

DECLARE

V_DNI PROFES.DNI%TYPE;

BEGIN

SELECT DNI INTO V_DNI FROM PROFES WHERE NOMBRE = :NEW.NOMBRE AND :NEW.APELLIDOS = APELLIDOS;

INSERT INTO RESERVAS VALUES (:NEW.DIA,:NEW.MES,:NEW.HORA,:NEW.CODAULA,:NEW.CODGRUPO,V_DNI);

EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO EXISTE PROFESOR');

WHEN DUP_VAL_ON_INDEX THEN

DBMS_OUTPUT.PUT_LINE('AULA OCUPADA');

END;