DROP TABLE CONEXIONES;
CREATE TABLE CONEXIONES (USUARIO VARCHAR2(30), FECHA DATE, EVENTO VARCHAR2(30),
NOMBRE_OBJ VARCHAR2(30), TIPO_OBJ VARCHAR2(30));


CREATE OR REPLACE TRIGGER CONEXION2
AFTER LOGON OR DDL
ON DATABASE
WHEN (ORA_LOGIN_USER = 'SYSTEM') 
BEGIN
INSERT INTO CONEXIONES VALUES (USER, SYSTIMESTAMP, ORA_SYSEVENT,
ORA_DICT_OBJ_NAME, ORA_DICT_OBJ_TYPE);
END;
/
