SELECT NOMBRE_CTA,COUNT(*) "N_MOVIMIENTOS" 
FROM MOVIMIENTOS M, CUENTAS C 
WHERE M.COD_BANCO=C.COD_BANCO
AND M.COD_SUCUR=C.COD_SUCUR
AND M.NUM_CTA=C.NUM_CTA
GROUP BY 
M.COD_BANCO,M.COD_SUCUR,M.NUM_CTA,NOMBRE_CTA
HAVING COUNT(*) = 
(SELECT MAX(COUNT(*)) FROM MOVIMIENTOS GROUP BY 
COD_BANCO,COD_SUCUR,NUM_CTA) 
/
