UPDATE CENTROS 
SET NUM_PLAZAS = NUM_PLAZAS/2 
WHERE COD_CENTRO IN (
SELECT COD_CENTRO FROM PROFESORES
GROUP BY COD_CENTRO
HAVING COUNT(COD_CENTRO)<2 
UNION
(SELECT COD_CENTRO FROM CENTROS MINUS
SELECT COD_CENTRO FROM PROFESORES))
/
