SELECT NOMBRE_SUC "Nombre Sucursal",SUM(SALDO_DEBE) "Suma Reintegro"
FROM CUENTAS C,SUCURSALES S
WHERE 
C.COD_BANCO=S.COD_BANCO
AND C.COD_SUCUR=S.COD_SUCUR
GROUP BY C.COD_BANCO,C.COD_SUCUR,NOMBRE_SUC
HAVING SUM(SALDO_DEBE) =
(SELECT MAX(SUM(SALDO_DEBE)) FROM CUENTAS GROUP BY
COD_BANCO,COD_SUCUR)
/
