/*ESCRIBE UNA FUNCION QUE RECIBA UNA FECHA Y DEVIELVA EL AÑO,
 EN NUMERO, CORRESPONDIENTE A ESA FECHA*/
CREATE OR REPLACE FUNCTION anio	(data DATE)
RETURN NUMBER
AS
	v_any NUMBER(4);
BEGIN
	v_any := TO_NUMBER(TO_CHAR(data, 'YYYY'));
	RETURN v_any;
END anio;
/

-- Escribir un bloque PL/SQL que haga uso de la función anterior.

DECLARE
 	n NUMBER(4);
BEGIN
 	n := anio(SYSDATE);
 	DBMS_OUTPUT.PUT_LINE('AÑO : '|| n);
END;
/
